# Generated by Django 4.1.7 on 2023-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='anonimouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pull',
            name='more_answers',
            field=models.BooleanField(default=False),
        ),
    ]
