# Generated by Django 4.1.7 on 2023-03-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0002_pull_anonimouse_pull_more_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='image',
        ),
    ]
